;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="BuildCategory.Dragons",NewTagName="BuildCategory.Dragon")
+GameplayTagList=(Tag="BuildCategory.Civic",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Defense",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Dragon",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Food",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Gathering",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Housing",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Magic",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Production",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Roads",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Storage",DevComment="")
+GameplayTagList=(Tag="Capacity.Housing",DevComment="How many people can live in the house")
+GameplayTagList=(Tag="Production.Lumber",DevComment="")
+GameplayTagList=(Tag="Resource.Food.Bread",DevComment="")
+GameplayTagList=(Tag="Resource.Food.CookedFish",DevComment="")
+GameplayTagList=(Tag="Resource.Food.CookedMeat",DevComment="")
+GameplayTagList=(Tag="Resource.Food.RawFish",DevComment="")
+GameplayTagList=(Tag="Resource.Food.RawMeat",DevComment="")
+GameplayTagList=(Tag="Resource.Food.Wheat",DevComment="")
+GameplayTagList=(Tag="Resource.Stone.RoughStone",DevComment="")
+GameplayTagList=(Tag="Resource.Wood.Logs",DevComment="")
+GameplayTagList=(Tag="ResourceCategory.Food",DevComment="")
+GameplayTagList=(Tag="ResourceCategory.Ore",DevComment="")
+GameplayTagList=(Tag="ResourceCategory.Stone",DevComment="")
+GameplayTagList=(Tag="ResourceCategory.Wood",DevComment="")
+GameplayTagList=(Tag="Road.MovementBonus",DevComment="")
+GameplayTagList=(Tag="Road.ProductionAccess",DevComment="")

