;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="BuildCategory.Dragons",NewTagName="BuildCategory.Dragon")
+GameplayTagList=(Tag="BuildCategory.Defense",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Dragon",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Food",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Gathering",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Housing",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Magic",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Production",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Roads",DevComment="")
+GameplayTagList=(Tag="BuildCategory.Storage",DevComment="")
+GameplayTagList=(Tag="Capacity.Housing",DevComment="How many people can live in the house")
+GameplayTagList=(Tag="Production.Lumber",DevComment="")
+GameplayTagList=(Tag="Resource.Bread",DevComment="")
+GameplayTagList=(Tag="Resource.Bronze",DevComment="")
+GameplayTagList=(Tag="Resource.Coal",DevComment="")
+GameplayTagList=(Tag="Resource.Copper",DevComment="")
+GameplayTagList=(Tag="Resource.Gold",DevComment="")
+GameplayTagList=(Tag="Resource.Iron",DevComment="")
+GameplayTagList=(Tag="Resource.Lumber",DevComment="")
+GameplayTagList=(Tag="Resource.Mana",DevComment="")
+GameplayTagList=(Tag="Resource.Steel",DevComment="")
+GameplayTagList=(Tag="Resource.Stone",DevComment="")
+GameplayTagList=(Tag="Resource.Tin",DevComment="")
+GameplayTagList=(Tag="Resource.Water",DevComment="")
+GameplayTagList=(Tag="Resource.Wheat",DevComment="")
+GameplayTagList=(Tag="Road.MovementBonus",DevComment="")
+GameplayTagList=(Tag="Road.ProductionAccess",DevComment="")

